default:
  image: node:latest

stages:
  - build
  - test

# Job's name
build:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - cd app
    - npm install
  artifacts:
    paths:
      - node_modules

unit-test:
  image: node:latest
  stage: test
  before_script:
    - cd app
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
